services:
  backend:
    build: ./backend
    container_name: url-shortener-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    command: yarn dev

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
    container_name: url-shortener-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: url-shortener-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: url-shortener

volumes:
  mongo-data:
